# docker-compose.yml
version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
  db:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.prod